### ISSUE TITLE
can i use the metric learn between images

### ISSUE THREAD

**Issue by shadow111** [all-umass/metric-learn#52]
Hello, please i want to know if i can use this implementation of metric learn to get similarity between images!!! if yes please can you just give me an example!!!
THank you so much

**Comment by perimosocordiae** [comment]
Sure, you can learn a similarity metric for images with the methods in this library. You'll need to convert them to vector form first, possibly using some other preprocessing methods as well.

Once you have a set of N images in a (N x D) matrix, you can use that to learn a metric. For instance:

```python
import numpy as np
from metric_learn import Covariance

# start with your images
images = [...]
# stack them up in vector form
X = np.row_stack([img.ravel() for img in images])
# learn the metric
cov = Covariance().fit(X)
# transform the image data to the new space
Xt = cov.transform(X)
# now you can use euclidean distance between rows in Xt
```

**Comment by shadow111** [comment]
Thnak you for your response!!
my own goel is to get if 2 images are similar or get a % for similarity!! can that be done !!!

**Comment by shadow111** [comment]
Hello,
i got error please can you tell me what i'm doing wrong ::
i have read 2 images using opencv imread
i add them into a list called images , here is my full code::
`import numpy as np
from metric_learn import Covariance
import cv2
images = []
I = cv2.imread("faces/face-0.jpg")
J = cv2.imread("faces/face-1.jpg")
images.append(I)
images.append(J)
X = np.row_stack([img.ravel() for img in images])
cov = Covariance().fit(X)
Xt = cov.transform(X)`

i got those error ::

`Traceback (most recent call last):
  File "metric.py", line 23, in <module>
    cov = Covariance().fit(X)
  File "/home/lafi/.local/lib/python2.7/site-packages/metric_learn/covariance.py", line 29, in fit
    self.M = np.cov(X.T)
  File "/home/lafi/.local/lib/python2.7/site-packages/numpy/lib/function_base.py", line 2928, in cov
    c = dot(X, X_T.conj())
MemoryError
`
please i need your help
THank you
Lafi
