### ISSUE TITLE
Bug when using verbose=True

### ISSUE THREAD

**Issue by andreydung** [all-umass/metric-learn#66]
```
ml = LSML(max_iter=100, verbose=True)
ml.fit(X, constraints)
```

```
Traceback (most recent call last):
  File "train_metric_lsml.py", line 62, in <module>
    ml.fit(X, constraints)
  File "/home/andrey/anaconda2/lib/python2.7/site-packages/metric_learn/lsml.py", line 96, in fit
    print('iter', it, 'cost', s_best, 'best step', l_best * grad_norm)
UnboundLocalError: local variable 'l_best' referenced before assignment
```

**Comment by andreydung** [comment]
Used the master branch, the problem is resolved. Maybe PyPi should be updated?

**Comment by perimosocordiae** [comment]
Yep, we're getting close to making a new release on PyPI. I want to address gh-57 first, though.
