### ISSUE TITLE
ValueError: failed to create intent(cache|hide)|optional array-- must have defined dimensions but got

### ISSUE THREAD

**Issue by GerrieWell** [all-umass/metric-learn#72]
Hi all-umass.
How to deal with huge dimension problem?
My input arrary shape like this : (12936, 35722).
I got error when call `lfda.fit` method.Here is the log output : 

```shell
  File "pp_lomoes_extrator.py", line 68, in lfda_learn
    self.lfda.fit(data,target)
  File "/home/wuyong/anaconda3/envs/py27/lib/python2.7/site-packages/metric_learn/lfda.py", line 102, in fit
    vals, vecs = scipy.linalg.eigh(tSb, tSw)
  File "/home/wuyong/anaconda3/envs/py27/lib/python2.7/site-packages/scipy/linalg/decomp.py", line 407, in eigh
    overwrite_b=overwrite_b)
ValueError: failed to create intent(cache|hide)|optional array-- must have defined dimensions but got (-1742630395,)
```

**Comment by GerrieWell** [comment]
Now I use the first 10000 dimension which small then data number. Still crash on this: 
```
Traceback (most recent call last):
  File "pp_lomoes_extrator.py", line 145, in <module>
    load_learn('../result/up_feats.npy','../result/target.npy')
  File "pp_lomoes_extrator.py", line 134, in load_learn
    lfda.fit(X,Y)
  File "/home/wuyong/anaconda3/envs/py27/lib/python2.7/site-packages/metric_learn/lfda.py", line 102, in fit
    vals, vecs = scipy.linalg.eigh(tSb, tSw)
  File "/home/wuyong/anaconda3/envs/py27/lib/python2.7/site-packages/scipy/linalg/decomp.py", line 445, in eigh
    " computed." % (info-b1.shape[0]))
numpy.linalg.linalg.LinAlgError: the leading minor of order 2269 of 'b' is not positive definite. The factorization of 'b' could not be completed and no eigenvalues or eigenvectors were computed.
```

**Comment by thomasbazeille** [comment]
Did you found a fix for that? Trying to use  linalg.eigh on 40000x40000 matrices still crashes for me with same error : 
`failed to create intent(cache|hide)|optional array-- must have defined dimensions but got (-1108792335,)`
